// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDER15SwrdskkDhWuG93ehHxF-9htbMG8Y',
    appId: '1:212991684869:web:309c3e022e83ff1657c76c',
    messagingSenderId: '212991684869',
    projectId: 'supervisor-solutions-b8160',
    authDomain: 'supervisor-solutions-b8160.firebaseapp.com',
    storageBucket: 'supervisor-solutions-b8160.firebasestorage.app',
    measurementId: 'G-4EQMCCW7WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACff4rgC502J9JheyQaWyXzxVHXlCCjhc',
    appId: '1:212991684869:android:de41d5241839dbac57c76c',
    messagingSenderId: '212991684869',
    projectId: 'supervisor-solutions-b8160',
    storageBucket: 'supervisor-solutions-b8160.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmzwQgjtQFrUaf-GbW41qoa4JWabXyu50',
    appId: '1:212991684869:ios:8ebadb6f6fba44d557c76c',
    messagingSenderId: '212991684869',
    projectId: 'supervisor-solutions-b8160',
    storageBucket: 'supervisor-solutions-b8160.firebasestorage.app',
    iosBundleId: 'com.example.chatbotAiFacilitated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmzwQgjtQFrUaf-GbW41qoa4JWabXyu50',
    appId: '1:212991684869:ios:8ebadb6f6fba44d557c76c',
    messagingSenderId: '212991684869',
    projectId: 'supervisor-solutions-b8160',
    storageBucket: 'supervisor-solutions-b8160.firebasestorage.app',
    iosBundleId: 'com.example.chatbotAiFacilitated',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDER15SwrdskkDhWuG93ehHxF-9htbMG8Y',
    appId: '1:212991684869:web:94e95b734f4b832b57c76c',
    messagingSenderId: '212991684869',
    projectId: 'supervisor-solutions-b8160',
    authDomain: 'supervisor-solutions-b8160.firebaseapp.com',
    storageBucket: 'supervisor-solutions-b8160.firebasestorage.app',
    measurementId: 'G-BXD61SHVNY',
  );
}
